os: Visual Studio 2017
version: "{build}"
configuration: Release
environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
  - choco install gitversion.portable -pre -y -r --no-progress
before_build:
  - dotnet restore
  - gitversion /output buildserver /updateAssemblyInfo
build:
    verbosity: minimal
after_build:
  - dotnet pack /p:Version="%GitVersion_NuGetVersion%"
artifacts:
  - path: "**\\*.nupkg"
